{
    "name": "Shopify Order Ops",
    "summary": "Two-way Odoo-Shopify sync with ops dashboard, orders, inventory, fulfillment, and more",
    "version": "19.0.1.0.64",
    "category": "Sales/Sales",
    "author": "Leeno Consult",
    "website": "https://apps.odoo.com",
    "license": "OPL-1",
    "price": 550.0,
    "currency": "USD",
    "depends": ["sale_management", "account", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/discount_direction_migrate.xml",
        "data/discount_catalogue_params.xml",
        "data/shopify_discount_product.xml",
        "data/dashboard_action.xml",
        "data/ops_pages_actions.xml",
        "views/sync_job_views.xml",
        "views/sync_log_views.xml",
        "views/stock_picking_views.xml",
        "views/location_map_views.xml",
        "views/product_views.xml",
        "views/metafield_map_views.xml",
        "views/discount_catalogue_views.xml",
        "views/sale_order_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "images": [
        "static/description/banner.png",
        "static/description/dashboard.png",
    ],
    "installable": True,
    "application": True,
    "assets": {
        "web.assets_backend": [
            "shopify_order_ops/static/src/js/dashboard.js",
            "shopify_order_ops/static/src/xml/dashboard.xml",
            "shopify_order_ops/static/src/css/dashboard.css",
        ],
    },
}
